### ISSUE TITLE
Component Style Change

### ISSUE THREAD

**Issue by sgr0691** [estevanmaito/windmill-react-ui#10]
Currently having trouble changing the styling to components. I've read the documentation for the windmill react ui repo but when it comes to changing colors would this need to happen in the myTheme.js file or in the tailwind.output.css file.

**Comment by estevanmaito** [comment]
Hey Sergio!

I would love to update the docs with a clearer explanation if it's not helpful in its current state. Did you try this? https://windmillui.com/react-ui/customization#customize-the-default-theme

You just need to create a file (name it whatever you want) in your project, and change the component colors there, then, in the same place you wrap your root component with `Windmill`, add a `theme` property to `Windmill` and pass it your custom them.

```jsx
import { Windmill } from '@windmill/react-ui'
import sergiosTheme from './sergiosTheme.js' // location of your custom theme

ReactDOM.render(
  <Windmill theme={sergiosTheme}>
    <App />
  </Windmill>,
  document.getElementById('root')
)
```

Let me know if it solves your problem.

**Comment by sgr0691** [comment]
Thanks Estevan! So in the index.js file it currently looks like this.
I tried to replaced the whole ReactDOM section with the code that you provided but it gives me multiple errors due to the ThemedSuspense component. Do I just delete that import ThemedSuspense line or is it essential for the dashboard? 

`import React, { Suspense } from 'react'
import ReactDOM from 'react-dom'
import './assets/css/tailwind.output.css'
import App from './App'
import { SidebarProvider } from './context/SidebarContext'
import ThemedSuspense from './components/ThemedSuspense'
import { Windmill } from '@windmill/react-ui'
import * as serviceWorker from './serviceWorker'

ReactDOM.render(
  <SidebarProvider>
    <Suspense fallback={<ThemedSuspense />}>
      <Windmill usePreferences>
        <App />
      </Windmill>
    </Suspense>
  </SidebarProvider>,
  document.getElementById('root')
)`

**Comment by estevanmaito** [comment]
Please share the errors.

**Comment by sgr0691** [comment]
![error](https://user-images.githubusercontent.com/8444737/91123243-6134e600-e66a-11ea-8ee2-dcbfcd8b00af.png)

**Comment by estevanmaito** [comment]
This (and all the code from your previous comment https://github.com/estevanmaito/windmill-react-ui/issues/10#issuecomment-679420483) is required: `<Suspense fallback={<ThemedSuspense />}>`

In order to add your theme, you gotta keep all the original code from the dashboard and add a prop to `Windmill` called `theme`, like you did in this last image.

Like:

```jsx
import React, { Suspense } from 'react'
import ReactDOM from 'react-dom'
import './assets/css/tailwind.output.css'
import App from './App'
import { SidebarProvider } from './context/SidebarContext'
import ThemedSuspense from './components/ThemedSuspense'
import { Windmill } from '@windmill/react-ui'
import * as serviceWorker from './serviceWorker'

// THIS IS WHERE YOU IMPORT YOUR THEME
// IT MAY HAVE A DIFFERENT NAME OR LOCATION
// 👇👇👇👇
import calyTheme from './calyTheme.js'

ReactDOM.render(
  <SidebarProvider>
    <Suspense fallback={<ThemedSuspense />}>
      {/* ADD YOUR THEME HERE, IN THE theme PROP */}
      {/*      👇👇👇 */}
      <Windmill theme={calyTheme} usePreferences>
        <App />
      </Windmill>
    </Suspense>
  </SidebarProvider>,
  document.getElementById('root')
)

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.register()
```

**Comment by sgr0691** [comment]
Okay great I just did that and it ran with no errors. To change the colors of the components would I then add them in the calyTheme.js file or in the tailwind output css file or the tailwind css file?

**Comment by estevanmaito** [comment]
You can follow the instructions here: https://windmillui.com/react-ui/customization#customize-the-default-theme

And here you find all the style properties available: https://github.com/estevanmaito/windmill-react-ui/blob/master/src/themes/default.js

You could just copy all the content of the file above (`default.js`) into your theme file and change just the colors if you find easier than pick individual styles.
