### ISSUE TITLE
Docs: Default theme customization

### ISSUE THREAD

**Issue by ptvandi** [estevanmaito/windmill-react-ui#19]
In the `Customization` section of the documentation, the link(s) to the default theme are outdated (they point to `default.js` instead of `default.ts`). 

Also, unless I'm doing it incorrectly, the note about importing the default theme is unclear:
> You can reference it in your code importing the default theme `windmill-react-ui/defaultTheme.`

I had to import it like so:
`import defaultTheme from '@windmill/react-ui/lib/defaultTheme';`

Thanks for the great work on this library!

**Comment by estevanmaito** [comment]
Fixed https://github.com/estevanmaito/windmill-ui-site/commit/caaa10ab3e452732a97ff2ae034937f7ad014837

Thanks for pointing!
