### ISSUE TITLE
Dropdown does not work with react 17

### ISSUE THREAD

**Issue by windgaucho** [estevanmaito/windmill-react-ui#20]
- `windmill-react-ui` version: 0.4.1

I am trying to use this library with react 17.0.1 and Dropdown does not work. On click on the dropdown menu it close automatically.

I must to downgrade to react 16.14.0 and it work ok.

**Comment by andregamma** [comment]
Same here, the onClose function is called on click for some reason, and then it closes.

**Comment by estevanmaito** [comment]
Thanks for reporting it!

It has something to do with the new way React 17 handles events.

As we are using `document` event listeners to catch clicks outside the dropdown and close it, things are broken now. I hope I can release a new version with this and other changes by the end of the week.

You can read more about the new behavior in React and why things are broken here: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues

**Comment by estevanmaito** [comment]
Solved and available in 0.5.0. Please, let me know if it doesn't solve your problem.
