### ISSUE TITLE
Alert exported undefined

### ISSUE THREAD

**Issue by sajas-nm** [estevanmaito/windmill-react-ui#29]
`import { Alert } from '@windmill/react-ui'`

 try it in both ways...

`<Alert   type="success"  onClose={() => { console.log('Close clicked'); }} message={"error"}   />`

`<Alert type="success">Lorem ipsum dolor sit</Alert>`

version  "@windmill/react-ui": "0.3.1",

**Comment by estevanmaito** [comment]
Alerts were included in 0.4.0

https://github.com/estevanmaito/windmill-react-ui/releases/tag/0.4.0
