### ISSUE TITLE
useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by estevanmaito** [estevanmaito/windmill-react-ui#3]
`windmill-react-ui` version: `0.1.0-alpha.8`

### Relevant code or config:

```jsx
import React from 'react'
import '../css/tailwind.css'
import { Windmill } from 'windmill-react-ui'

function MyApp({ Component, pageProps }) {
  return (
    <Windmill>
      <Component {...pageProps} />
    </Windmill>
  )
}

export default MyApp

```

### What you did:
Rendered `Windmill` component with NextJS

### What happened:

```sh
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

### Reproduction:

Docs repo of this project (not available yet)

**Comment by estevanmaito** [comment]
Need to dig a little more into this, but:

1. It's just a warning
2. It's probably related to the `useLayoutEffect` that is responsible for the theme. If that is the case, then it's not solvable with `useEffect`, as the _layout_ here is needed to avoid a flash of light theme when the user actually prefers dark, which is stored in `localStorage` (client only) and should run as soon as possible.

Will keep it open to remind me.

**Comment by ronyfhebrian** [comment]
Hi! what is the solution for `useLayoutEffect` bug?
Thank you.

**Comment by estevanmaito** [comment]
@ronyfhebrian Please, refer to the comment above yours. It's a warning and it's needed to render the component only on client.

**Comment by franky-chanyau** [comment]
A mismatch in server rendered UI and client side UI is a potential dealbreaker for us folks using [Styled JSX](https://github.com/vercel/styled-jsx) but since wrapping the app in the `<Windmill/>` does not stop us from using the packaged components. Following the [This handy article](https://nextjs.org/blog/styling-next-with-styled-jsx), you can create your own app wrapper component and theme file to modify component styles as needed using [Windmill's theme defaults](https://github.com/estevanmaito/windmill-react-ui/blob/master/src/themes/default.ts) as reference.

Not ideal, we're out here in the tailwind v2 and React 17 world. Still a handy UI library though. Appreciate your work!

**Comment by mattgi** [comment]
This was a workaround to get things going on `nextjs`

`components/render-where.tsx`
```
import React, { useEffect, useState } from "react";

export interface ConditionallyRenderProps {
  client?: boolean;
  server?: boolean;
}

export const RenderWhere: React.FC<ConditionallyRenderProps> = (props) => {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => setIsMounted(true), []);

  if (!isMounted && props.client) {
    return null;
  }

  if (isMounted && props.server) {
    return null;
  }

  return props.children as React.ReactElement;
};
```

`pages/_app.tsx`
```
import "../styles/tailwind.css";

import { Windmill } from "@windmill/react-ui";
import { AppProps } from "next/app";
import Head from "next/head";
import * as React from "react";

import { RenderWhere } from "../components/render-where";

export default function App({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>App</title>
      </Head>
      <RenderWhere server>
        <Component {...pageProps} />
      </RenderWhere>
      <RenderWhere client>
        <Windmill>
          <Component {...pageProps} />
        </Windmill>
      </RenderWhere>
    </>
  );
}
```

**Comment by cassus** [comment]
The `RenderWhere` workaround re-renders the whole page so for example form element loose their state, so not ideal.

@estevanmaito would you consider using `useIsomorphicLayoutEffect` ?

It avoids the warning for SSR:

```js
const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffect : useEffect;
```

Source and details: https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a

**Comment by mrofi** [comment]
This comment works for me.

https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85#gistcomment-3886909

Just put this in ```pages/_app.js``` or some other top-level place:

```
// suppress useLayoutEffect warnings when running outside a browser
if (!process.browser) React.useLayoutEffect = React.useEffect;
```
useLayoutEffect and useEffect have the same argument signature, and neither runs if we're not in a browser.
So if we're not in a browser it's safe to globally replace the one that triggers warnings with the one that doesn't.
