### ISSUE TITLE
.form-input class breaks with Tailwind v2

### ISSUE THREAD

**Issue by mhatvan** [estevanmaito/windmill-react-ui#48]
- `windmill-react-ui` version: 0.5.0

### What you did:

In development, the form inputs have a border and are styled, but when building a production bundle, the .form-input class loses some properties and the input style is messed up.

You can see a difference between applied styles in development and production here:

DEV
![Screenshot from 2021-03-26 17-21-33](https://user-images.githubusercontent.com/16797721/112662559-1bd2d400-8e58-11eb-82a1-7ea23af5bce4.png)

PROD
![Screenshot from 2021-03-26 17-21-49](https://user-images.githubusercontent.com/16797721/112662561-1d040100-8e58-11eb-87e1-05a8fe0c3de7.png)

**Comment by estevanmaito** [comment]
Fixed with 0.6.0
