### ISSUE TITLE
Responsive Layout templates

### ISSUE THREAD

**Issue by scalarerp** [estevanmaito/windmill-react-ui#6]
Meu, que massssssaaaa, tá show, nota dez.

Minha sugestão é fazer um boilerplate para web pages ou landing pages, que todo mundo vai utilizar.

Tem um cara muito legal que fez um milhao de exemplos grátis aqui: https://treact.owaiskhan.me/

Layouts de w-full ou centralizados, com colunas, ficaria muito massa.

Quando descer a serra te pago o almoço aqui em IVOTI-RS.

**Comment by estevanmaito** [comment]
😂😂

Pretendo fazer um modelo de landing no futuro, mas nada parecido com o que esse projeto ai ta fazendo. Parece uma copia do Tailwind UI 😬 Pra dar uma treta de licença...

O que eu fiz usando essa lib foi essa dashboard aqui: https://github.com/estevanmaito/windmill-dashboard-react
