### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by atreya2011** [estevanmaito/windmill-react-ui#9]
**Is your feature request related to a problem? Please describe.**
As of now, there is no TypeScript support.

**Describe the solution you'd like**
Would you consider a pull request with typings written for each component?

**Comment by estevanmaito** [comment]
> Would you consider a pull request with typings written for each component?

Yes! I'm getting started with TS, but it would take some time for me to do this, so feel free to PR.

Just a reminder: run `npm run cz` instead of `git commit` to keep the standard commit message and you're good!

**Comment by atreya2011** [comment]
Understood regarding `npm run cz` and thanks for the feedback! I will start working on the type definitions shortly :)

**Comment by estevanmaito** [comment]
I'm not considering a PR rewriting the code to TS for the fact that I wouldn't be able to verify it, so I will refactor it in the future (around a month or when I feel comfortable with TS - but this is my priority now over new components).

For now, typings for each component would be appreciated.

**Comment by atreya2011** [comment]
Understood :) @estevanmaito

**Comment by HerbCaudill** [comment]
Estevan - really strong work on this project, parabéns! 

I see on [twitter](http://twitter.com/estevanmaito/status/1303394278794842112) that you've made good progress with the Typescript migration - is there any way I can help?

**Comment by estevanmaito** [comment]
@HerbCaudill Gracias!

I'm like 95% done, but really got stuck with some details in 2 or 3 components. I'll try to PR until the end of the week so you guys can take a look at it.

**Comment by estevanmaito** [comment]
Your help would be greatly appreciated here -> #14 
 
All feedback and suggestions are welcome!

**Comment by estevanmaito** [comment]
Release: https://github.com/estevanmaito/windmill-react-ui/releases/tag/0.4.0-beta.0
Available as beta also `npm i @windmill/react-ui@beta`

Landing as a stable version later this week if everything is ok.

**Comment by tracy-codes** [comment]
@estevanmaito I'll install on an internal project that uses this library + Typescript and will report any issues we encounter!

**Comment by estevanmaito** [comment]
Closing as it is already merged and will be naturally upgraded from beta soon.

Feel free to comment any issue.

**Comment by atreya2011** [comment]
This is great! Sorry I couldn't contribute in the end. I am planning on using the components in a new project and will report issues if I find any 🙇🏻‍♂️

**Comment by AwsafAlam** [comment]
@estevanmaito  is the typescript branch being maintained? Will it be updated as newer components are added?

**Comment by estevanmaito** [comment]
@AwsafAlam not a branch. It's already part of the master and the current release. New components will be added as soon as I finish the Tailwind update (working on it, but limited free time unfortunately :/).
